### ISSUE TITLE
Version Decrement and Rename

### ISSUE THREAD

**Issue by jngls** [vectorgameexperts/bevy-async-task#9]
Hey, might be worth leaving a note on the front page for a few months to say that the crate was renamed and version number changed. We had to go digging to work out what happened.

**Comment by nuzzles** [comment]
Yeah, it's in the CHANGELOG, but that might not be good enough. I'd be fine taking with a PR for this.

As a result, versions were reset back to 0.1.

It was pulled from crates.io by the Crates team so we could republish with underscores instead of kebab case. (e.g. `bevy_async_task` instead of `bevy-async-task`)
